### ISSUE TITLE
usually the voltage range for source voltage is -0.1V to 5.1V

### ISSUE THREAD

**Issue by luciansin** [analogdevicesinc/Pixelpulse2#202] opened 2016-07-21 10:10 UTC
Usually you can enter a value lower than 0V(lower limit is -0.1V) and higher than 5V(higher limit is 5.1V) for voltage. When this happens the signals are cutoff.
There are also times when you cannot introduce a value outside this range [0V;5V], but I wasn't able to reproduce what cause that and this good behavior happens rarely. Most often you can set a value outside the range.
![screenshot from 2016-07-21 16-36-56](https://cloud.githubusercontent.com/assets/4027921/17019191/d1e13060-4f43-11e6-9f10-798fd6174221.png)

**Comment by AlexandraTrifan** [comment] 2016-07-21 13:56
Fixed with commit 662434be72892fa0f5d15420b27ad9b8c0390ed9.

**Comment by AlexandraTrifan** [comment] 2018-09-05 14:33
Tested on v1.0.4. Can't reproduce it anymore. 
I will close this.

**Closed by AlexandraTrifan** 2018-09-05 14:33 UTC
Labels: Fixed, bug
