### ISSUE TITLE
Found the problem- need help

### ISSUE THREAD

**Issue by jaganmail** [analogdevicesinc/Pixelpulse2#156] opened 2015-12-03 13:36 UTC
The windows file is working fine in 64 bit windows 7 & not having problem in 32 bit (fonts not visible and  graph not visible). Please help me with 32 bit windows executable. 

Thanks in advance

**Comment by acozma** [comment] 2015-12-04 14:09
Closing since it's a duplicate of issue #155

**Closed by acozma** 2015-12-04 14:09 UTC
Labels: duplicate
